[build]
  # Directory to publish (relative to root of your repo)
  publish = "frontend/dist"
  # New build command that creates a VERSION file to force redeployment
  command = "echo \"Version: $(date)\" > VERSION && rm -rf netlify/functions && mkdir -p netlify/functions && cp -r backend/functions/* netlify/functions/ && cd frontend && npm install && npm run build && cd .. && npm install @google/generative-ai"

# Explicitly create a redirect for the chat endpoint
[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (define these in the Netlify dashboard)
[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_YARN = "false"
  NETLIFY_CACHE_FUNCTIONS = "false"

# Functions directory for serverless functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Mark the dependency as external
  external_node_modules = ["@google/generative-ai"]
  included_files = ["VERSION"]  # Include the version file

# Force Netlify to use the latest code, not cached versions
[build.processing]
  skip_processing = false
